/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchivoRouteImport } from './routes/archivo'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as CompatibilidadRouteImport } from './routes/compatibilidad'
import { Route as HerramientasRouteImport } from './routes/herramientas'
import { Route as ModeloRouteImport } from './routes/modelo'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ComponentesIndexRouteImport } from './routes/componentes/index'
import { Route as ComponentesSlugRouteImport } from './routes/componentes/$slug'
import { Route as DispositivosIndexRouteImport } from './routes/dispositivos/index'
import { Route as DispositivosSlugRouteImport } from './routes/dispositivos/$slug'
import { Route as LiquidosIndexRouteImport } from './routes/liquidos/index'
import { Route as LiquidosSlugRouteImport } from './routes/liquidos/$slug'
import { Route as ResistenciasIndexRouteImport } from './routes/resistencias/index'
import { Route as ResistenciasSlugRouteImport } from './routes/resistencias/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchivoRoute = ArchivoRouteImport.update({
  id: '/archivo',
  path: '/archivo',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const CompatibilidadRoute = CompatibilidadRouteImport.update({
  id: '/compatibilidad',
  path: '/compatibilidad',
  getParentRoute: () => rootRouteImport,
} as any)
const HerramientasRoute = HerramientasRouteImport.update({
  id: '/herramientas',
  path: '/herramientas',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeloRoute = ModeloRouteImport.update({
  id: '/modelo',
  path: '/modelo',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentesIndexRoute = ComponentesIndexRouteImport.update({
  id: '/componentes/',
  path: '/componentes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentesSlugRoute = ComponentesSlugRouteImport.update({
  id: '/componentes/$slug',
  path: '/componentes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DispositivosIndexRoute = DispositivosIndexRouteImport.update({
  id: '/dispositivos/',
  path: '/dispositivos/',
  getParentRoute: () => rootRouteImport,
} as any)
const DispositivosSlugRoute = DispositivosSlugRouteImport.update({
  id: '/dispositivos/$slug',
  path: '/dispositivos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquidosIndexRoute = LiquidosIndexRouteImport.update({
  id: '/liquidos/',
  path: '/liquidos/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquidosSlugRoute = LiquidosSlugRouteImport.update({
  id: '/liquidos/$slug',
  path: '/liquidos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResistenciasIndexRoute = ResistenciasIndexRouteImport.update({
  id: '/resistencias/',
  path: '/resistencias/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResistenciasSlugRoute = ResistenciasSlugRouteImport.update({
  id: '/resistencias/$slug',
  path: '/resistencias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archivo': typeof ArchivoRoute
  '/buscar': typeof BuscarRoute
  '/comparar': typeof CompararRoute
  '/compatibilidad': typeof CompatibilidadRoute
  '/herramientas': typeof HerramientasRoute
  '/modelo': typeof ModeloRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/componentes/$slug': typeof ComponentesSlugRoute
  '/dispositivos/$slug': typeof DispositivosSlugRoute
  '/liquidos/$slug': typeof LiquidosSlugRoute
  '/resistencias/$slug': typeof ResistenciasSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/componentes/': typeof ComponentesIndexRoute
  '/dispositivos/': typeof DispositivosIndexRoute
  '/liquidos/': typeof LiquidosIndexRoute
  '/resistencias/': typeof ResistenciasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archivo': typeof ArchivoRoute
  '/buscar': typeof BuscarRoute
  '/comparar': typeof CompararRoute
  '/compatibilidad': typeof CompatibilidadRoute
  '/herramientas': typeof HerramientasRoute
  '/modelo': typeof ModeloRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/componentes/$slug': typeof ComponentesSlugRoute
  '/dispositivos/$slug': typeof DispositivosSlugRoute
  '/liquidos/$slug': typeof LiquidosSlugRoute
  '/resistencias/$slug': typeof ResistenciasSlugRoute
  '/blog': typeof BlogIndexRoute
  '/componentes': typeof ComponentesIndexRoute
  '/dispositivos': typeof DispositivosIndexRoute
  '/liquidos': typeof LiquidosIndexRoute
  '/resistencias': typeof ResistenciasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archivo': typeof ArchivoRoute
  '/buscar': typeof BuscarRoute
  '/comparar': typeof CompararRoute
  '/compatibilidad': typeof CompatibilidadRoute
  '/herramientas': typeof HerramientasRoute
  '/modelo': typeof ModeloRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/componentes/$slug': typeof ComponentesSlugRoute
  '/dispositivos/$slug': typeof DispositivosSlugRoute
  '/liquidos/$slug': typeof LiquidosSlugRoute
  '/resistencias/$slug': typeof ResistenciasSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/componentes/': typeof ComponentesIndexRoute
  '/dispositivos/': typeof DispositivosIndexRoute
  '/liquidos/': typeof LiquidosIndexRoute
  '/resistencias/': typeof ResistenciasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archivo'
    | '/buscar'
    | '/comparar'
    | '/compatibilidad'
    | '/herramientas'
    | '/modelo'
    | '/blog/$slug'
    | '/componentes/$slug'
    | '/dispositivos/$slug'
    | '/liquidos/$slug'
    | '/resistencias/$slug'
    | '/blog/'
    | '/componentes/'
    | '/dispositivos/'
    | '/liquidos/'
    | '/resistencias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archivo'
    | '/buscar'
    | '/comparar'
    | '/compatibilidad'
    | '/herramientas'
    | '/modelo'
    | '/blog/$slug'
    | '/componentes/$slug'
    | '/dispositivos/$slug'
    | '/liquidos/$slug'
    | '/resistencias/$slug'
    | '/blog'
    | '/componentes'
    | '/dispositivos'
    | '/liquidos'
    | '/resistencias'
  id:
    | '__root__'
    | '/'
    | '/archivo'
    | '/buscar'
    | '/comparar'
    | '/compatibilidad'
    | '/herramientas'
    | '/modelo'
    | '/blog/$slug'
    | '/componentes/$slug'
    | '/dispositivos/$slug'
    | '/liquidos/$slug'
    | '/resistencias/$slug'
    | '/blog/'
    | '/componentes/'
    | '/dispositivos/'
    | '/liquidos/'
    | '/resistencias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchivoRoute: typeof ArchivoRoute
  BuscarRoute: typeof BuscarRoute
  CompararRoute: typeof CompararRoute
  CompatibilidadRoute: typeof CompatibilidadRoute
  HerramientasRoute: typeof HerramientasRoute
  ModeloRoute: typeof ModeloRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ComponentesSlugRoute: typeof ComponentesSlugRoute
  DispositivosSlugRoute: typeof DispositivosSlugRoute
  LiquidosSlugRoute: typeof LiquidosSlugRoute
  ResistenciasSlugRoute: typeof ResistenciasSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ComponentesIndexRoute: typeof ComponentesIndexRoute
  DispositivosIndexRoute: typeof DispositivosIndexRoute
  LiquidosIndexRoute: typeof LiquidosIndexRoute
  ResistenciasIndexRoute: typeof ResistenciasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archivo': {
      id: '/archivo'
      path: '/archivo'
      fullPath: '/archivo'
      preLoaderRoute: typeof ArchivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compatibilidad': {
      id: '/compatibilidad'
      path: '/compatibilidad'
      fullPath: '/compatibilidad'
      preLoaderRoute: typeof CompatibilidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herramientas': {
      id: '/herramientas'
      path: '/herramientas'
      fullPath: '/herramientas'
      preLoaderRoute: typeof HerramientasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelo': {
      id: '/modelo'
      path: '/modelo'
      fullPath: '/modelo'
      preLoaderRoute: typeof ModeloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/componentes/': {
      id: '/componentes/'
      path: '/componentes'
      fullPath: '/componentes/'
      preLoaderRoute: typeof ComponentesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/componentes/$slug': {
      id: '/componentes/$slug'
      path: '/componentes/$slug'
      fullPath: '/componentes/$slug'
      preLoaderRoute: typeof ComponentesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispositivos/': {
      id: '/dispositivos/'
      path: '/dispositivos'
      fullPath: '/dispositivos/'
      preLoaderRoute: typeof DispositivosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispositivos/$slug': {
      id: '/dispositivos/$slug'
      path: '/dispositivos/$slug'
      fullPath: '/dispositivos/$slug'
      preLoaderRoute: typeof DispositivosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquidos/': {
      id: '/liquidos/'
      path: '/liquidos'
      fullPath: '/liquidos/'
      preLoaderRoute: typeof LiquidosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquidos/$slug': {
      id: '/liquidos/$slug'
      path: '/liquidos/$slug'
      fullPath: '/liquidos/$slug'
      preLoaderRoute: typeof LiquidosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resistencias/': {
      id: '/resistencias/'
      path: '/resistencias'
      fullPath: '/resistencias/'
      preLoaderRoute: typeof ResistenciasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resistencias/$slug': {
      id: '/resistencias/$slug'
      path: '/resistencias/$slug'
      fullPath: '/resistencias/$slug'
      preLoaderRoute: typeof ResistenciasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchivoRoute: ArchivoRoute,
  BuscarRoute: BuscarRoute,
  CompararRoute: CompararRoute,
  CompatibilidadRoute: CompatibilidadRoute,
  HerramientasRoute: HerramientasRoute,
  ModeloRoute: ModeloRoute,
  BlogSlugRoute: BlogSlugRoute,
  ComponentesSlugRoute: ComponentesSlugRoute,
  DispositivosSlugRoute: DispositivosSlugRoute,
  LiquidosSlugRoute: LiquidosSlugRoute,
  ResistenciasSlugRoute: ResistenciasSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ComponentesIndexRoute: ComponentesIndexRoute,
  DispositivosIndexRoute: DispositivosIndexRoute,
  LiquidosIndexRoute: LiquidosIndexRoute,
  ResistenciasIndexRoute: ResistenciasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
